version: "3"

services:
  frontend:
    container_name: frontend
    build:
      dockerfile: Dockerfile
      context: ./frontend
      args:
        - MAVEN_REPO_USER=${MAVEN_REPO_USER}
        - MAVEN_REPO_PASS=${MAVEN_REPO_PASS}
        - MAVEN_REPO_URL=${MAVEN_REPO_URL}
    ports:
      - "80:8080"
    volumes:
      - ./frontend/target/frontend.war:/usr/local/tomcat/webapps/ROOT.war
  backend:
    container_name: backend
    build:
      dockerfile: Dockerfile
      context: ./backend
      args:
        - MAVEN_REPO_USER=${MAVEN_REPO_USER}
        - MAVEN_REPO_PASS=${MAVEN_REPO_PASS}
        - MAVEN_REPO_URL=${MAVEN_REPO_URL}
    ports:
      - "8080:8080"
    volumes:
      - ./backend/target/backend.war:/usr/local/tomcat/webapps/ROOT.war
