image: maven:latest

stages:
  - build
  - test
  - deploy

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode --errors --fail-at-end"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/
    - target/

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS compile
    # build .war file # http://albert-kuo.blogspot.com/2018/01/gitlab-how-to-build-war-file.html
    - mvn clean package -U
  artifacts:
    when: always
    paths:
    - target/*.war

test:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS test

deploy:
  stage: deploy
  script:
    # install sshpass that is a tool to work with ssh access
    - apt-get update -qq && apt-get install -y -qq sshpass
    - sshpass -V
    # login with ssh to server then scp the build file deployment
    - sshpass -p $SSHPASS scp -o stricthostkeychecking=no -r target/backend.war $SSHUSER@46.101.241.48:/var/lib/tomcat8/webapps